server:
  port: 8087

spring:
  application:
    name: api-user
  zipkin:
    baseUrl: http://localhost:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

info:
  application:
    name: api-user

eureka:
  healthcheck:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/