server:
  port: 8078

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-account
          uri: lb://api-account
          predicates:
            - Path=/api/v1/account/**
        - id: ms-user
          uri: lb://api-user
          predicates:
            - Path=/api/v1/user/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: api-gateway