server:
  port: 8080

spring:
  application:
    name: api-user
  zipkin:
    baseUrl: http://zipkin:9411/
  datasource:
    url: jdbc:mysql://mysql-user:3306/user_db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

info:
  application:
    name: api-user

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  healthcheck:
    enabled: true
    registry-fetch-interval-seconds: 5
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  instance:
    hostname: api-user
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Configuraciones de heartbeat más frecuentes
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    # Especifica la URL de health check
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enable: true
    rabbit:
      enable: false
