server:
  port: 8080

spring:
  application:
    name: api-payment
  zipkin:
    baseUrl: http://zipkin:9411/
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    url: jdbc:mysql://mysql-payment:3306/payment_db
    username: ${PAYMENT_DB_USER}
    password: ${PAYMENT_DB_PASS}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

  resilience4j:
    circuitBreaker:
      instances:
        paymentService:
          registerHealthIndicator: true
          slidingWindowSize: 10
          minimumNumberOfCalls: 5
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 5s
          failureRateThreshold: 50
    retry:
      instances:
        paymentService:
          maxAttempts: 3
          waitDuration: 1s
    rateLimiter:
      instances:
        paymentService:
          limitForPeriod: 10
          limitRefreshPeriod: 1s
          timeoutDuration: 0s

info:
  application:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: api-payment
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics